//register & login
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const CONFIRMATION_SUCCESS = 'CONFIRMATION_SUCCESS';
export const CONFIRMATION_NEEDED = 'CONFIRMATION_NEEDED';
export const CONFIRMATION_FAILED = 'CONFIRMATION_FAILED';

//system
export const GET_EXCHANGE_RATE = 'GET_EXCHANGE_RATE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const CLEAR_FINANCE = 'CLEAR_FINANCE';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SYSTEM_ERROR = 'SYSTEM_ERROR';

//profile
export const SET_PROFILE = 'SET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_LOADING_ON = 'PROFILE_LOADING_ON';

//categories
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SINGLE_CATEGORY = 'GET_SINGLE_CATEGORY';
export const CATEGORIES_LOADING_ON = 'CATEGORIES_LOADING_ON';
export const CATEGORIES_LOADING_OFF = 'CATEGORIES_LOADING_OFF';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

//incomes
export const ADD_INCOME = 'ADD_INCOME';
export const GET_INCOMES = 'GET_INCOMES';
export const GET_SINGLE_INCOME = 'GET_SINGLE_INCOME';
export const UPDATE_INCOME = 'UPDATE_INCOME';
export const UPDATE_ACTIVE_INCOME = 'UPDATE_ACTIVE_INCOME';
export const INCOMES_LOADING_ON = 'INCOMES_LOADING_ON';
export const INCOMES_LOADING_OFF = 'INCOMES_LOADING_OFF';
export const INCOME_ERROR = 'INCOME_ERROR';
export const DELETE_INCOME = 'DELETE_INCOME';

//transactions
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
export const GET_TRANSACTIONS_BY_INCOME = 'GET_TRANSACTIONS_BY_INCOME'
export const GET_TRANSACTIONS_BY_CATEGORY = 'GET_TRANSACTIONS_BY_CATEGORY'
export const DELETE_SINGLE_TRANSACTION = 'DELETE_SINGLE_TRANSACTION'
export const DELETE_RELATED_TRANSACTIONS = 'DELETE_RELATED_TRANSACTIONS'
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR'
export const TRANSACTIONS_LOADING_ON = 'TRANSACTIONS_LOADING_ON'
export const TRANSACTIONS_BY_CATEGORY_LOADING_ON = 'TRANSACTIONS_BY_CATEGORY_LOADING_ON'
export const TRANSACTIONS_BY_INCOME_LOADING_ON = 'TRANSACTIONS_BY_INCOME_LOADING_ON'
